name: onlinebozor
description: onlinebozor is online marketplace
publish_to: 'none'

version: 1.3.4+1032

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  android_id: ^0.3.6
  auto_route: ^7.8.2
  badges: ^3.1.2
  bloc: ^8.1.2
  blur: ^3.1.0
  cached_network_image: ^3.2.3
#  firebase_analytics: ^11.0.1
#  firebase_core: ^3.1.0
#  firebase_crashlytics: ^4.0.1
#  firebase_remote_config: ^5.0.1
  flutter_cache_manager: ^3.3.2
  calendar_date_picker2: ^0.5.3
  camerapreview: ^0.0.1
  carousel_slider: ^4.0.0
  chucker_flutter: ^1.6.0
  collection: ^1.17.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.11
  device_info_plus: ^9.0.2
  dio: ^5.3.2
  easy_localization: ^3.0.2
  easy_localization_loader: ^2.0.0
  elegant_notification: ^1.11.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  external_app_launcher: ^4.0.0
  floor: ^1.4.2
  flutter_bloc: ^8.1.3
  flutter_date_pickers: ^0.4.2
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_shimmer_widget: ^1.1.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  get_it: ^7.6.0
  image_picker: ^0.8.1
  injectable_generator: ^2.4.1
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  logger: ^2.0.1
  mask_text_input_formatter: ^2.5.0
  modal_bottom_sheet: ^3.0.0
  multi_select_flutter: ^4.1.3
  package_info_plus: ^4.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  pretty_dio_logger: ^1.3.1
  smooth_page_indicator: ^1.0.0
  sms_autofill: ^2.3.1
  sqflite: ^2.3.3+1
  share_plus: ^7.2.2
  shimmer: ^3.0.0
  tab_indicator_styler: ^2.0.0
  url_launcher: ^6.1.14
  webview_flutter: ^4.7.0
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  easy_localization_generator: ^0.3.1
  floor_generator: ^1.4.2
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png_images/app_logo.png"


flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_medium.ttf
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_semi_bold.ttf
  uses-material-design: true

  assets:
    - assets/localization/
    - assets/images/
    - assets/images/png_images/
    - assets/images/bottom_bar/

flutter_gen:
  output: lib/core/gen/assets/
  integrations:
    flutter_svg: true