name: onlinebozor
description: onlinebozor is online marketplace
publish_to: 'none'

version: 1.0.2+1001

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.2
  easy_localization_loader: ^2.0.0
  get_it: ^7.6.0
  injectable: ^2.3.0
  logger: ^2.0.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1
  auto_route: ^7.8.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  elegant_notification: ^1.11.0
  collection: ^1.17.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  easy_localization_generator: ^0.3.1
  mask_text_input_formatter: ^2.5.0
  cached_network_image: ^3.2.3
  infinite_scroll_pagination: ^4.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  tab_indicator_styler: ^2.0.0
  android_id: ^0.3.6
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.1
  path_provider: ^2.1.1
  chucker_flutter: ^1.6.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.3.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png_images/app_logo.png"


flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
  uses-material-design: true

  assets:
    - assets/localization/
    - assets/images/
    - assets/images/profile/
    - assets/images/png_images/
    - assets/images/bottom_bar/
    - assets/images/profile_viewer/

flutter_gen:
  output: lib/common/gen/assets/
  integrations:
    flutter_svg: true